# Generated by Django 4.1.2 on 2022-11-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'cuisine',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cust_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('pword', models.CharField(blank=True, max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotel_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('field_hotel_name', models.CharField(db_column='\u2002\u2002\u2002\u2002hotel_name', max_length=50)),
                ('address', models.CharField(max_length=40)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('amenities', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'hotel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('manager_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('pword', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.CharField(blank=True, max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'manager',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('room_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('hotel_id', models.CharField(max_length=5)),
                ('reser_time', models.TimeField()),
                ('checkin', models.TimeField()),
                ('checkout', models.TimeField()),
            ],
            options={
                'db_table': 'reservation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('review_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(blank=True)),
                ('comments', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'reviews',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('room_type', models.CharField(max_length=15)),
                ('available', models.CharField(max_length=3)),
                ('price', models.CharField(max_length=6)),
                ('air_conditioned', models.BooleanField()),
                ('accomodities', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'room',
                'managed': False,
            },
        ),
    ]
