# Generated by Django 4.1.2 on 2022-11-07 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
