# Generated by Django 4.1.2 on 2022-11-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_app', '0002_delete_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=10)),
                ('hotel_id', models.CharField(max_length=5)),
                ('reser_time', models.TimeField()),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
            ],
            options={
                'db_table': 'reservation',
                'managed': False,
            },
        ),
    ]
