# Generated by Django 4.1.2 on 2022-11-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_app', '0003_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelRelation',
            fields=[
                ('relation', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'hotel_relation',
                'managed': False,
            },
        ),
    ]
